
FROM node:20 AS build
WORKDIR /app

COPY webapp/package*.json ./
RUN npm install

COPY webapp/ ./
COPY webapp/set-env.js ./

ARG PRODUCTION
ARG BASE_URL

RUN PRODUCTION=$PRODUCTION BASE_URL=$BASE_URL node set-env.js
RUN npm run build --prod

FROM nginx:alpine
COPY --from=build /app/dist/webapp/browser /usr/share/nginx/html
COPY webapp/nginx.conf /etc/nginx/nginx.conf

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]