services:
  backendapp:
    build:
      context: .
      dockerfile: Dockerfile
      target: final
    volumes:
      - ./logs:/app/logs
    ports:
      - '8080:8080'
    depends_on:
      - db

  webapp:
    environment:
      - PRODUCTION=true
      - BASE_URL=http://3.1.251.146:8080
    build:
      context: .
      dockerfile: Dockerfile.angular
      args:
        PRODUCTION: 'true'
        BASE_URL: 'http://3.1.251.146:8080'
    ports:
      - '80:80'

  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_DB: freelancer
      POSTGRES_USER: cdn-db-user
      POSTGRES_PASSWORD: Testing@1234
    ports:
      - '5432:5432'
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
