@hostAddress = http://localhost:5007
### @hostAddress = http://3.1.251.146:8080

POST {{hostAddress}}/v1/user/register
Content-Type: application/json

{
    "email": "zaidaiman@gmail.com",
    "username": "zaidaiman",
    "phoneNumber": "0123456789",
    "skillsets": [""]
}

###

GET {{hostAddress}}/v1/auth/token/zaidaiman
Content-Type: application/json

###

GET {{hostAddress}}/v1/user/search?sort=createdAt&sort=username
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6InphaWRhaW1hbiIsIm5iZiI6MTcyNjk0OTgzNSwiZXhwIjoxNzI2OTUzNDM1LCJpYXQiOjE3MjY5NDk4MzUsImlzcyI6IkNvbXBsZXRlIERldmVsb3BlciBOZXR3b3JrIiwiYXVkIjoiQ29tcGxldGUgRGV2ZWxvcGVyIE5ldHdvcmsgQVBJIn0.5I-TUIlCHzsiKMA3GrDyK-myFKdEvWOG8hTf_hA45K0

###